name: Rocom Merchant Bot

on:
  schedule:
    # 这里必须写 UTC 时间 (北京时间 - 8)
    # 23:55 UTC = 07:55 北京 (前一天/当天)
    # 03:55 UTC = 11:55 北京
    # 07:55 UTC = 15:55 北京
    # 11:55 UTC = 19:55 北京
    - cron: '55 23,3,7,11 * * *'
  workflow_dispatch:

jobs:
  check_merchant:
    runs-on: ubuntu-latest
    # 设置整个任务的环境变量为上海时区
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install httpx

      - name: Run script
        env:
          MY_API_KEY: ${{ secrets.WEGAME_API_KEY }}
          MY_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK_URL }}
        run: python main.py
