name: Rocom Merchant Bot

on:
  schedule:
    # 这里必须写 UTC 时间 (北京时间 - 8)
    # 00:00 UTC = 08:00 北京
    # 04:00 UTC = 12:00 北京
    # 08:00 UTC = 16:00 北京
    # 12:00 UTC = 20:00 北京
    - cron: '0 0,4,8,12 * * *'
  workflow_dispatch:

jobs:
  check_merchant:
    runs-on: ubuntu-latest
    # 【新增】设置整个任务的环境变量为上海时区
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install httpx

      - name: Run script
        env:
          MY_API_KEY: ${{ secrets.WEGAME_API_KEY }}
          MY_WEBHOOK: ${{ secrets.WECHAT_WEBHOOK_URL }}
        run: python main.py
